xxl:
  job:
    admin:
      address: http://msgcloud-core-job-admin:8080/xxl-job-admin
    executor:
      appname: msgcloud-core-executor-base
      ip: msgcloud-core-executor-base
      port: 10000
      logpath: /data/applogs/msg-core-executor/msg-core-executor-base/
      logretentiondays: 30
      accessToken:

web-url:
  nation-station-data: http://39.106.9.232/obs_station/