rocketmq:
  name-server: namesrv:9876
  producer:
    group: msgcloud-core-message

spring:
  cloud:
    nacos:
      discovery:
        server-addr: msgcloud-nacos:8848/

path:
  chromedriver: /usr/bin/chromedriver
  tmp: /tmp/
  ffmpeg: /usr/local/ffmpeg/bin/ffmpeg