server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: msgcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msgcloud-service-msgcenter
          uri: lb://msgcloud-service-msgcenter
          predicates:
            - Path=/api/msgcenter/**
        - id: msgcloud-service-datacenter
          uri: lb://msgcloud-service-datacenter
          predicates:
            - Path=/api/datacenter/**

logging:
  config: classpath:log/logbak.xml